#!/system/bin/sh
#
# W.I.P. script, by USBhost. made for the Nexus 9.
# this script is most likely universal to devises that
# has ZRAM and/or SWAP enabled.
#
# i use busybox for some commands because
# in the hopes of them being newer.
#

log -p i -t FI.d:01afterboot " FIRE-ICE script v27 "

# overclocking.
# CPU 2.5 ghz
# GPU 0.984 ghz
## (0 = disabled) (1 = enabled)
	OC=0

# CPU Interactive Governor fix.
# this will increase battery life
# but with some lag.
## (0 = disabled) (1 = enabled)
	Gfix=0

# fsync
## (0 = disabled) (1 = default/enabled)
	FS=1

# fast charge.
## (0 = default/disabled) (1 = enabled)
	FC=1

# double tap to wake
## (0 = disabled) (1 = default/enabled)
	DTW=1

# set debug to NO.
	echo 0 > /sys/kernel/debug/debug_enabled

# I/O tweaks
	echo 0 > /sys/block/mmcblk0/queue/add_random
	echo 768 > /sys/block/mmcblk0/queue/read_ahead_kb

# entropy tweaks
	echo 320 > /proc/sys/kernel/random/write_wakeup_threshold
	echo 256 > /proc/sys/kernel/random/read_wakeup_threshold

#   ------------------------<MEMORY>-----------------------   #

# set working cores, thats used with zram.
	core="$(cat /proc/cpuinfo | grep -c processor)"

# Ultra Kernel Samepage Merging
## (0 = default/disabled) (1 = enabled) ##
	UKSM=1

# config memory.
	#echo 10972 > /proc/sys/vm/extra_free_kbytes # FIXME: testing, let system set it
	echo 5486 > /proc/sys/vm/min_free_kbytes
	echo 100 > /proc/sys/vm/vfs_cache_pressure
	echo 60 > /proc/sys/vm/swappiness
	echo 0 > /proc/sys/vm/page-cluster # FIXME: this should be restored in the ramdisk 

# config Low Memory Killer / keep within the bounds
	chmod 644 /sys/module/lowmemorykiller/parameters/minfree # FIXME: this should be fixed in the ramdisk
	echo "18432,23040,27648,32256,36864,41472" > /sys/module/lowmemorykiller/parameters/minfree

# turn off Low Memory Killer.
# ONLY! if your vary, vary memory conscious
# and always clears recents, then you can use this!
# if your not memory conscious things will go wrong!
## (0 = disabled) (1 = enabled) ##
	LMK=0

# Adaptive LMK
# prevents sluggishness and provides very low app 
# launch latency by making LMK more dynamically aggressive.
# note: this may use more battery.
## (0 = disabled) (1 = enabled) ##
	AMK=0

# ZRAM.
# "raid" and "aswap" will be null.
# you can still use cswap but it
# will be second priority.
## (0 = disabled) ##
	zswap=0 # zswap is in MB.

# swap in cache.
# will make a swap file in /cache.
# cswap must not go over 150
# or f2fs /cache will not work.
## (0 = disabled) ##
	cswap=0 # cswap is in MB.

# make /cache all swap.
# cswap will be null if enabled.
# swap will be 260MB, 520MB if "raid" = 1 .
# note: cache will be formated.
## (0 = disabled) (1 = enabled) ##
	aswap=0

# use zswap and cswap
# with a raid 0 like way.
## (0 = disabled) (1 = enabled) ##
	raid=0

#   ------------------------<EXPERT>-----------------------   #

# Load override
if [ -e /sdcard/override ]; then
	log -p i -t FI.d:01afterboot " override; loading "
	. /sdcard/override
else
	log -p i -t FI.d:01afterboot " no override; skipping "
fi
if [ "$UKSM" == "1" ]; then
	echo 1000 > /sys/kernel/mm/uksm/sleep_millisecs
	echo 1 > /sys/kernel/mm/uksm/run
fi
if [ "$cswap" -ge "1" ] && [ "$aswap" == "0" ]; then
	if [ -e /cache/swap ]; then
		if [ "$zswap" -ge "1" ] && [ "$raid" == "0" ]; then
			/BB/busybox swapon -p 1 /cache/swap # with zram
		elif [ "$zswap" == "0" ] && [ "$raid" == "1" ]; then
			/BB/busybox swapon -p 2 /cache/swap # raid 0
		elif [ "$zswap" == "0" ] && [ "$raid" == "0" ]; then
			/BB/busybox swapon -d /cache/swap # solo
		fi
	else
		dd if=/dev/zero of=/cache/swap bs="$cswap"m count=1
		chmod 600 /cache/swap
		/BB/busybox mkswap /cache/swap
		if [ "$zswap" -ge "1" ] && [ "$raid" == "0" ]; then
			/BB/busybox swapon -d -p 1 /cache/swap # with zram
		elif [ "$zswap" == "0" ] && [ "$raid" == "1" ]; then
			/BB/busybox swapon -d -p 2 /cache/swap # raid 0
		elif [ "$zswap" == "0" ] && [ "$raid" == "0" ]; then
			/BB/busybox swapon -d /cache/swap # solo
		fi
	fi
	if [ "$zswap" == "0" ] && [ "$raid" == "1" ]; then
		echo 1 > /sys/block/zram0/reset
		echo 1 > /sys/block/zram0/max_comp_streams
		echo lz4 > /sys/block/zram0/comp_algorithm
		echo "$cswap"M > /sys/block/zram0/disksize
		/BB/busybox mkswap /dev/block/zram0
		/BB/busybox swapon -d -p 2 /dev/block/zram0
	fi
fi
if [ "$zswap" == "0" ] && [ "$aswap" == "1" ]; then
	umount /cache
	/BB/busybox mount -t tmpfs -o rw tmpfs /cache && log -p i -t FI.d:01afterboot " mounted cache as tmpfs "
	/BB/busybox mkswap /dev/block/platform/sdhci-tegra.3/by-name/CAC # FIXME: make it run only once
	/BB/busybox swapon -d -p 1 /dev/block/platform/sdhci-tegra.3/by-name/CAC
	if [ "$raid" == "1" ]; then
		echo 1 > /sys/block/zram0/reset
		echo 1 > /sys/block/zram0/max_comp_streams
		echo lz4 > /sys/block/zram0/comp_algorithm
		echo 260M > /sys/block/zram0/disksize
		/BB/busybox mkswap /dev/block/zram0
		/BB/busybox swapon -d -p 1 /dev/block/zram0
	fi
fi
if [ "$zswap" -gt "1" ] && [ "$aswap" == "0" ]; then
	echo 1 > /sys/block/zram0/reset
	echo "$core" > /sys/block/zram0/max_comp_streams
	echo lz4 > /sys/block/zram0/comp_algorithm
	#echo 600M > /sys/block/zram0/mem_limit # safety limit
	echo "$zswap"M > /sys/block/zram0/disksize
	/BB/busybox mkswap /dev/block/zram0
	/BB/busybox swapon -d -p 2 /dev/block/zram0
fi
if [ "$LMK" == "1" ]; then
	echo 0 > /sys/module/lowmemorykiller/parameters/minfree  
fi
if [ "$AMK" == "1" ]; then
	echo 1 > /sys/module/lowmemorykiller/parameters/enable_adaptive_lmk
	echo 46080 > /sys/module/lowmemorykiller/parameters/vmpressure_file_min
fi
if [ "$OC" == "1" ]; then
	echo 2499000 > /sys/module/cpu_tegra/parameters/cpu_user_cap
elif [ "$OC" == "0" ]; then
	echo 1 > /sys/kernel/tegra_gpu/gpu_cap_state
	echo 852000000 > /sys/kernel/tegra_gpu/gpu_cap_rate
fi
if [ "$Gfix" == "1" ]; then
	echo 612000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
	echo "65 510000:75 714000:85" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
	chmod 444 /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
	chmod 444 /sys/devices/system/cpu/cpufreq/interactive/target_loads
fi
if [ "$DTW" == "0" ]; then
	echo 0 > /sys/devices/platform/spi-tegra114.2/spi_master/spi2/spi2.0/input/input0/wake_gesture
fi
if [ "$FS" == "0" ]; then
	echo 0 > /sys/module/sync/parameters/fsync_enabled
fi
if [ "$FC" == "1" ]; then
	echo 1 > /sys/kernel/fast_charge/force_fast_charge
fi
if [ -e /cache/swap ] && [ "$cswap" == "0" ]; then
	rm /cache/swap
fi
