#!/system/bin/sh
#
# W.I.P. script, made by USBhost.
# for this script to work you need busbox.
# made for the Nexus 9.
#

# overclocking.
## (0 = disabled) (1 = enabled)
	OC=0

# CPU Interactive Governor fix.
	echo 612000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
	echo "65 510000:75 714000:85" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
	# lock.
	chmod 444 /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
	chmod 444 /sys/devices/system/cpu/cpufreq/interactive/target_loads

# fsync.
## (0 = disabled) (1 = enabled)
	echo 1 > /sys/module/sync/parameters/fsync_enabled

# fast charge.
## (0 = disabled) (1 = enabled)
	echo 1 > /sys/kernel/fast_charge/force_fast_charge

# its here just to be here
# if disabled you will get problems with sleep.
	#echo 0 > /sys/devices/platform/spi-tegra114.2/spi_master/spi2/spi2.0/input/input0/wake_gesture

# set debug to NO.
	echo N > /sys/kernel/debug/debug_enabled

#   ------------------------<MEMORY>-----------------------   #

# Ultra Kernel Samepage Merging
## (0 = disabled) (1 = enabled)
	echo 1 > /sys/kernel/mm/uksm/run

# config swap.
	echo 80 > /proc/sys/vm/swappiness
	echo 3 > /proc/sys/vm/page-cluster

# config Low Memory Killer.
	echo "17920,20480,23040,25600,28160,30720" > /sys/module/lowmemorykiller/parameters/minfree

# ZRAM (ONLY!)
## (0 = disabled) (1 = enabled)
# zrswap and aswap must be disabled.
# you can use cswap but it will be
# in second priority.
# zsize is in MB.
	zram=0
	zsize=0

# cache swap
## (0 = disabled) (1 = enabled)
# will make a swap file in /cache.
# czsize must not go over 150
# or f2fs /cache wont work.
# czsize is in MB.
	cswap=1
	czsize=130

# compressed cache swap file
## (0 = disabled) (1 = enabled)
# pages that are in the process of being 
# swapped then attempts to compress them.
	zswap=1

# make /cache all swap
## (0 = disabled) (1 = enabled)
# cswap and czsize will be null
# if enabled. swap will be 260 MB.
	aswap=0

# use zram with cache
## (0 = disabled) (1 = enabled)
# with a raid 0 like way.
	zrswap=1

#   ------------------------<EXPERT>-----------------------   #

if [ "$cswap" == "1" ] && [ "$aswap" == "0" ] && [ "$zrswap" == "0" ] && [ -e /cache/swap ]; then
	chmod 1777 /cache/swap
	mkswap /cache/swap
	swapon -p 1 /cache/swap
elif [ "$cswap" == "1" ] && [ "$aswap" == "0" ]; then
	if [ -e /cache/swap ]; then
		chmod 1777 /cache/swap
		fstrim -v /cache || log -p i -t FI.d " fstrim faild "
		mkswap /cache/swap
	else
		dd if=/dev/zero of=/cache/swap bs="$czsize"m count=1
		chmod 1777 /cache/swap
		fstrim -v /cache || log -p i -t FI.d " fstrim faild "
		mkswap /cache/swap
	fi
	if [ "$zram" == "1" ]; then
		swapon -p 2 /cache/swap
	else
		swapon -p 1 /cache/swap
	fi
	if [ "$zrswap" == "1" ]; then
		echo 1 > /sys/block/zram0/reset
		echo lz4 > /sys/block/zram0/comp_algorithm
		echo "$czsize"M > /sys/block/zram0/disksize
		mkswap /dev/block/zram0
		swapon -p 1 /dev/block/zram0
	fi
fi
if [ "$aswap" == "1" ]; then
	umount /cache
	busybox mount -t tmpfs -o rw,noatime tmpfs /cache
	mkswap /dev/block/platform/sdhci-tegra.3/by-name/CAC
	swapon -p 1 /dev/block/platform/sdhci-tegra.3/by-name/CAC
	if [ "$zrswap" == "1" ]; then
		echo 1 > /sys/block/zram0/reset
		echo lz4 > /sys/block/zram0/comp_algorithm
		echo 260M > /sys/block/zram0/disksize
		mkswap /dev/block/zram0
		swapon -p 1 /dev/block/zram0
	fi
fi
if [ -e /cache/swap ] && [ "$cswap" == "0" ] && [ "$zrswap" == "0" ] && [ "$aswap" == "0" ]; then
	chmod 777 /cache/swap
	rm /cache/swap
elif [ "$zram" == "1" ] && [ "$zrswap" == "0" ] && [ "$aswap" == "0" ]; then
	echo 1 > /sys/block/zram0/reset
	echo lz4 > /sys/block/zram0/comp_algorithm
	echo "$zsize"M > /sys/block/zram0/disksize
	mkswap /dev/block/zram0
	swapon -p 1 /dev/block/zram0
fi
if [ "$zswap" == "1" ]; then
	chmod 755 /sys/module/zswap/parameters/enabled
	chmod 755 /sys/module/zswap/parameters/compressor
	echo lz4 > /sys/module/zswap/parameters/compressor
	echo 1 > /sys/module/zswap/parameters/enabled
fi
if [ "$OC" == "1" ]; then
	echo 2499000 > /sys/module/cpu_tegra/parameters/cpu_user_cap
elif [ "$OC" == "0" ]; then
	echo 1 > /sys/kernel/tegra_gpu/gpu_cap_state
	echo 852000000 > /sys/kernel/tegra_gpu/gpu_cap_rate
fi
	
