#!/system/bin/sh
#
# W.I.P. script, made by USBhost.
# for this script to work you'll need busbox,
# if not supplied. made for the Nexus 9.
#

# resume suspend
	echo 1 > /sys/class/htc_sensorhub/sensor_hub/led_en
	sleep 2
	echo 0 > /sys/class/htc_sensorhub/sensor_hub/led_en
	echo tmp_lock > /sys/power/wake_unlock && log -p i -t FI.d " Done "
