#!/system/bin/sh


cache_on () 
{
	if [ "$zram" == "1" ] && [ "$cswap" == "1" ]; then
		/BB/busybox swapon -d -p 1 /cache/swap
	elif 
		/BB/busybox swapon -d -p 2 /cache/swap
	fi
}

mk_swap () 
{
	chmod 600 /cache/swap
	/BB/busybox fstrim -v /cache
	/BB/busybox mkswap /cache/swap
}

mk_cache () 
{
	dd if=/dev/zero of=/cache/swap bs="$czsize"m count=1
}

mk_zram ()
{
	echo 1 > /sys/block/zram0/reset
	echo 3 > /sys/block/zram0/max_comp_streams
	echo lz4 > /sys/block/zram0/comp_algorithm
	if [ "$aswap" == "1" ] && [ "$zram" == "0" ]; then
		echo "$czsize"M > /sys/block/zram0/disksize
	else
		echo 260M > /sys/block/zram0/disksize
	fi
	/BB/busybox mkswap /dev/block/zram0
}

zram_on () 
{
	/BB/busybox swapon -d -p 2 /dev/block/zram0
}
