#!/system/bin/sh
#
# W.I.P. script, by USBhost. made for the Nexus 9.
#

# i know of 3 things that like to kill battery
# com.google.android.gms:snet :: cpu usage of this process is lowish but can get high also uses a good amount of I/O
# and shoots cpu frequency to the max speed.
# com.google.android.gms.persistent :: this is known to go bad but its rare and when it does everyone knows it
# com.google.android.gms.unstable :: this seems to only go bad if snet is killed/frozen and you will know when it goes bad

mod=1; # 0 debug (no killing) / 1 start (killing)

L=/data/kill.log;
PS=/system/etc/FI.d/lib/ps;
date >> /data/kill.log;
while sleep 10;
do
	${PS} -A -o %cpu,cmd | grep com.google.android.gms | grep -v dex2oat | while read -r percent process;
	do
		cpu_usage=${percent%.*};
		cpu0=$(< /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq);
		if [ "${mod}" = "1" ] && [ "${cpu0}" -gt "1020000" ] && [ "${cpu_usage}" -ge "30" ]; then
			# Note this will kill unstable a lot but 
			# killing it has little consequence
			echo "Killing: ${process} CPU:${cpu_usage%}% F:${cpu0} $(date "+%H:%M:%S")" >> $L;
			killall -9 "${process}";
		elif [ "${mod}" = "0" ] && [ "${cpu_usage}" -ge "20" ]; then
				echo "Log: ${process} CPU:${cpu_usage%} F:${cpu0} $(date "+%H:%M:%S")" >> $L;
		fi
	done
done
