#!/system/bin/sh
#
# W.I.P. script, by USBhost.
#
# I use busybox for some commands because
# in the hopes of them being newer.
#
# The 'FI.d' folder
# is meant for values that do not stay at boot

# Load Symbols
	. /system/etc/FI.d/symbols;

# Script pacific Symbol
	LC="start";

# Wake lock is needed because if the system suspends
# FI.d/init.d scripts will not run.
	echo tmp_lock > /sys/power/wake_lock;
	$LOGCATI$LC "$(id)";

# Mount cache
	# FIXME: 00start doesn't know if cache is swap.
	MCACHE;
	if [ "$MCACHE" == "" ]; then 
		$BB mount -t auto -o rw $CACHE /cache;
		MCACHE;
		if [ "$MCACHE" != "$CACHE" ]; then
        		$LOGCATI$LC " cache; mount failed ";
		elif [ "$MCACHE" == "$CACHE" ]; then
			$LOGCATI$LC " cache; mount successful ";
			$BB fstrim /cache;
		fi
	elif [ "$MCACHE" == "$CACHE" ]; then
		$LOGCATI$LC " cache; is already mounted ";
	fi

# Start init.d
	if [ ! -e /system/bin/sysinit ]; then
		$BB run-parts /system/etc/init.d;
	fi

# SuperSU system root
	#if [ ! -e /data/su.img ]; then
	#	/system/xbin/bash /init.bash_SU.sh;
	#fi

