#!/system/bin/sh
#
# W.I.P. script, by USBhost.
#

# debug FI.d
	set -x

	# busybox location
BB="/system/etc/FI.d/lib/busybox";
	# zram's sys interface
ZRS="/sys/block/zram0";
	# zram's block device
ZRB="/dev/block/zram0";
	# cpu cores
CORE="$(cat /proc/cpuinfo | grep -c processor)";
	# override file
ORID="/sdcard/override";
	# cache partition location
CACHE="/dev/block/platform/sdhci-tegra.3/by-name/CAC";
	# cache partition size
PSIZE="256";
	# cache swap file
CSWAP="/cache/swap";
	# for info logs
LOGCATI="log -p i -t FI.d:";
	# for warning logs
LOGCATW="log -p w -t FI.d:";


	# size of cswap
function CSIZE() 
{
	CSIZE="$($BB du -h $CSWAP | $BB grep -o $cswap)";
}
	# cache mount check
function MCACHE() 
{
	MCACHE="$($BB mount | $BB grep -o $CACHE)";
}
