#!/system/bin/sh
#
# W.I.P. script, by USBhost. made for the Nexus 9.
#

#set -x

#globle
BB="/system/etc/FI.d/lib/busybox";
MF="USB";
MP="/data/media/0/${MF}";
MFP="/sdcard/${MF}";

function helpd() {
	supported=$(cat /proc/filesystems | grep -v nodev)
	echo "
Usage: -m BLOCK FILE-SYSTEM // like -m sda f2fs
Note: if FILE-SYSTEM is not specified (like -m sda )
for mount auto will be used insted.

    -h -------------------- display this help
    -u -------------------- umount drive
    -m BLOCK FILE-SYSTEM -- mount drive
    -r BLOCK FILE-SYSTEM -- repair drive
    -f BLOCK FILE-SYSTEM -- format drive

Supported file systems (to mount): 
${supported}"
}

# list mount points
function listd() {
	for f in /dev/block/sd*; 
	do 
		echo "${f##*/}"; 
	done
}

# mount
function mountd() {
	mkdir -p ${MFP};
	
	if [ "${3}" != "" ]; then
		if [ "${3}" == "ntfs" ]; then
			${SUPERUS} ${BB} mount -t ${3} -o rw,umask=000,nls=utf8 /dev/block/${2} ${MP};
		elif [ "${3}" == "exfat" ]; then
			${SUPERUS} ${BB} mount -t ${3} -o rw,umask=000 /dev/block/${2} ${MP};
		else
			${SUPERUS} ${BB} mount -t ${3} -o rw /dev/block/${2} ${MP};
		fi
	else
		${SUPERUS} ${BB} mount -t auto -o rw /dev/block/${2} ${MP};
	fi
	
	echo "Mounted: ${MP}";
	echo "Access here: ${MFP}";
}

# umount
function umountd() {
	${BB} umount -l ${MP};
	echo "Unmounted: ${MP}";
}

# format tools
function formatd() {
	f2fs="/system/bin/make_f2fs";
	ext4="/system/bin/make_ext4fs";

	if [ "${3}" != "" ]; then
		umountd;
		
		if [ "${3}" == "f2fs" ]; then
			${f2fs} /dev/block/${2};
			mountd - ${2} f2fs;
			chmod -R 777 ${MP};
		elif [ "${3}" == "ext4" ]; then
			${ext4} /dev/block/${2};
			mountd - ${2} ext4;
			chmod -R 777 ${MP};
		elif [ "${3}" == "ntfs" ]; then
			echo "not supported yet";
		elif [ "${3}" == "vfat" ]; then
			echo "not supported yet";
		elif [ "${3}" == "exfat" ]; then
			echo "not supported yet";
		fi
	fi
}

# repair tools
function repaird() {
	f2fs="/system/bin/fsck.f2fs";
	ext="/system/bin/e2fsck";
	
	function extcheck() {
		if [ "${3}" == "ext2" ] ||
			[ "${3}" == "ext3" ] ||
			[ "${3}" == "ext4" ]; then
			echo "dont use ${3}, use ext instead";
			exit 1;
		fi
	}

	if [ "${3}" != "" ]; then
		extcheck ${@};
		umountd;
		
		if [ "${3}" == "f2fs" ]; then
			${f2fs} -a /dev/block/${2};
		elif [ "${3}" == "ext" ]; then
			${ext} -vy /dev/block/${2};
		elif [ "${3}" == "ntfs" ]; then
			echo "not supported yet";
		elif [ "${3}" == "vfat" ]; then
			echo "not supported yet";
		elif [ "${3}" == "exfat" ]; then
			echo "not supported yet";
		fi
	fi
}

if [ "$(whoami)" != "root" ]; then
	echo "ROOT is required";
	echo "use usb -h for help";
	exit 1;
fi

if [ "$(su -v | grep -o SUPERSU)" == "SUPERSU" ]; then
	SUPERUS="su --mount-master -c";
fi

while getopts lum:f:r:h opt; do
    case $opt in
        l) listd;
            ;;
        u) umountd;
            ;;
        m) mountd ${@};
            ;;
        f) formatd ${@};
            ;;
        r) repaird ${@};
            ;;
        h) helpd;
            ;;
        *) helpd;
            ;;
    esac
done
